server:
  port: 8080
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: 'create-drop'
  cache:
    type: REDIS
  redis:
    port: 6379
    host: localhost

  datasource:
    url: jdbc:mysql://localhost:3306/invest
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: akhil
    password: akhil
