server:
  port: 8080
spring:
  jpa:
#    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: 'create-drop'
  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
    url: jdbc:mysql://localhost:3306/invest
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: akhil
    password: akhil
